import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { NavBar } from "@/components/ui/tubelight-navbar";
import { StackedCircularFooter } from "@/components/ui/stacked-circular-footer";

const monasans = Mona_Sans({
  variable: "--font-mona-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${monasans.className} antialiased pattern`}>
        <NavBar />
        {children}
        <StackedCircularFooter />
        <Toaster />
      </body>
    </html>
  );
}
